# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 15:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IDgenerator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderdetails',
            name='AOI',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='riderdetails',
            name='bicycle',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='riderdetails',
            name='chapter',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='riderdetails',
            name='terrain',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
        ),
    ]
