# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IDgenerator', '0002_auto_20170323_1512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RiderDetails',
            new_name='Rider',
        ),
        migrations.AlterModelTable(
            name='rider',
            table='riders',
        ),
    ]
