# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IDgenerator', '0003_auto_20170324_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rider',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
